---
# Please keep alphabetic order
env:
  node: false
extends:
  - next/core-web-vitals
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - unused-imports
root: true
rules:
  '@typescript-eslint/consistent-type-imports':
    - error
  '@typescript-eslint/no-duplicate-imports':
    - error
  '@typescript-eslint/explicit-module-boundary-types':
    - error
  '@typescript-eslint/naming-convention':
    - warn
    - format:
        - camelCase
      selector: function
    - format:
        - camelCase
      selector: variableLike
    - format:
        - camelCase
        - UPPER_CASE
        - PascalCase
      modifiers:
        - const
      selector: variable
    - custom:
        match: false
        regex: ^(I[A-Z]|_I[A-Z])
      format:
        - PascalCase
      selector: interface
    - format:
        - PascalCase
      selector: typeLike
  camelcase: 'off'
  comma-dangle:
    - error
    - arrays: always-multiline
      exports: always-multiline
      functions: always-multiline
      imports: always-multiline
      objects: always-multiline
  comma-spacing: error
  complexity:
    - error
    - 12
  eol-last: error
  import/no-deprecated: warn
  import/no-extraneous-dependencies: error
  import/order:
    - error
  indent: 'off'
  keyword-spacing: error
  max-len:
    - warn
    - code: 160
  no-async-promise-executor: 'off'
  no-case-declarations: 'off'
  no-dupe-class-members: 'off'
  no-duplicate-imports: 'off'
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces: error
  no-unused-vars: 'off'
  no-use-before-define: 'off'
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  prefer-const: error
  prettier/prettier: error
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - never
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars: error
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
      moduleDirectory:
        - node_modules
      paths:
        - /usr/local/share/global_modules
