name: Public pages

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg NODE_VERSION="$(cat .nvmrc)" -t dashboard .
      - run: docker run --rm --env GIT_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} dashboard yarn publish
