name: Public pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg NODE_VERSION="$(cat .nvmrc)" -t dashboard .
      - run: docker run --rm --volume=$(pwd)/out:/app/out dashboard yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out
